//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVC_SSRS_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBank
    {
        public int Id { get; set; }
        public string BankName { get; set; }
        public int BankCode { get; set; }
    }
}
